sudo: required
services:
    - docker

before_install:
    - docker build -t praneethkat/docker -f Dockerfile.dev .
    - 
script:
    - docker run -e CI=true praneethkat/docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-627002216967"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"